apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper
spec:
  clusterIP: None
  selector:
    app: clickhouse-keeper
  ports:
    - protocol: TCP
      port: 9181
      targetPort: 9181
      name: zookeeper
    - protocol: TCP
      port: 9234
      targetPort: 9234
      name: raft
