---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config-templates-configmap-v1
data:
  global.xml.template: >
    <clickhouse>
      <logger>
        <level>debug</level>
        <log>/dev/stdout</log>
        <errorlog>/dev/stderr</errorlog>
      </logger>
      <display_name>${DISPLAY_NAME}</display_name>
      <listen_host>0.0.0.0</listen_host>
      <http_port>8123</http_port>
      <tcp_port>9000</tcp_port>
    </clickhouse>
  keeper.xml.template: >
    <clickhouse>
      <zookeeper>
        <node>
          <host>clickhouse-keeper-0.clickhouse-keeper</host>
          <port>9181</port>
        </node>
        <node>
          <host>clickhouse-keeper-1.clickhouse-keeper</host>
          <port>9181</port>
        </node>
        <node>
          <host>clickhouse-keeper-2.clickhouse-keeper</host>
          <port>9181</port>
        </node>
      </zookeeper>
    </clickhouse>
  macros.xml.template: >
    <clickhouse>
      <shard>${SHARD_ID}</shard>
      <replica>${REPLICA_ID}</replica>
      <cluster>cluster_5S_3R</cluster>
    </clickhouse>
  remote-servers.xml.template: >
    <clickhouse>
      <remote_servers replace="true">
        <cluster_5S_3R>
          <secret>${REPLICA_SECRET}</secret>
            <shard>
              <internal_replication>true</internal_replication>
              <replica>
                <host>clickhouse-server-0.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-5.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-10.clickhouse-server</host>
                <port>9000</port>
              </replica>
            </shard>

            <shard>
              <internal_replication>true</internal_replication>
              <replica>
                <host>clickhouse-server-1.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-6.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-11.clickhouse-server</host>
                <port>9000</port>
              </replica>
            </shard>

            <shard>
              <internal_replication>true</internal_replication>
              <replica>
                <host>clickhouse-server-2.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-7.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-12.clickhouse-server</host>
                <port>9000</port>
              </replica>
            </shard>

            <shard>
              <internal_replication>true</internal_replication>
              <replica>
                <host>clickhouse-server-3.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-8.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-13.clickhouse-server</host>
                <port>9000</port>
              </replica>
            </shard>

            <shard>
              <internal_replication>true</internal_replication>
              <replica>
                <host>clickhouse-server-4.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-9.clickhouse-server</host>
                <port>9000</port>
              </replica>
              <replica>
                <host>clickhouse-server-14.clickhouse-server</host>
                <port>9000</port>
              </replica>
            </shard>

        </cluster_5S_3R>
      </remote_servers>
    </clickhouse>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-usersd-configmap-v1
data:
  empty.xml: >
    <clickhouse>
    </clickhouse>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-initd-configmap-v1
data:
  01-render-config.sh: >
    \#!/bin/sh

    apk add envsubst

    SERVER_ID=${SERVER_ID##*-}
    SHARD_ID=$(( SERVER_ID % 5 ))
    REPLICA_ID=$(( SERVER_ID % 3 ))
    REPLICA_SECRET=changeme   # TODO: use proper secret storage

    envsubst < /etc/zookeeper-config/templates/macros.xml.template > /etc/zookeeper-config/config.d/macros.xml
    envsubst < /etc/zookeeper-config/templates/global.xml.template > /etc/zookeeper-config/config.d/global.xml
    envsubst < /etc/zookeeper-config/templates/keeper.xml.template > /etc/zookeeper-config/config.d/keeper.xml
    envsubst < /etc/zookeeper-config/templates/remote-servers.xml.template > /etc/zookeeper-config/config.d/remote-servers.xml
