---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config-templates-configmap-v1
data:
  global.xml.template: >
    <clickhouse>
      <logger>
        <level>debug</level>
        <log>/dev/stdout</log>
        <errorlog>/dev/stderr</errorlog>
      </logger>
      <display_name>${DISPLAY_NAME}</display_name>
      <listen_host>0.0.0.0</listen_host>
      <http_port>8123</http_port>
      <tcp_port>9000</tcp_port>
    </clickhouse>
  keeper.xml.template: >
    <clickhouse>
      <zookeeper>
        <node>
          <host>clickhouse-keeper-0.clickhouse-keeper</host>
          <port>9181</port>
        </node>
        <node>
          <host>clickhouse-keeper-1.clickhouse-keeper</host>
          <port>9181</port>
        </node>
        <node>
          <host>clickhouse-keeper-2.clickhouse-keeper</host>
          <port>9181</port>
        </node>
      </zookeeper>
    </clickhouse>
  macros.xml.template: >
    <clickhouse>
      <shard>${SHARD_ID}</shard>
      <replica>${REPLICA_ID}</replica>
    </clickhouse>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-usersd-configmap-v1
data:
  empty.xml: >
    <clickhouse>
    </clickhouse>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-initd-configmap-v1
data:
  01-render-config.sh: >
    \#!/bin/sh

    apk add envsubst

    SERVER_ID=${SERVER_ID##*-}
    SHARD_ID=${SERVER_ID}
    REPLICA_ID=$(( SERVER_ID % 3 ))

    envsubst < /etc/zookeeper-config/templates/macros.xml.template > /etc/zookeeper-config/config.d/macros.xml
    envsubst < /etc/zookeeper-config/templates/global.xml.template > /etc/zookeeper-config/config.d/global.xml
    envsubst < /etc/zookeeper-config/templates/keeper.xml.template > /etc/zookeeper-config/config.d/keeper.xml
